version: "3"
name: uweflix

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: uweflix
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"
    expose:
      - "3307"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-P", "3307", "-u", "root", "-p12345678", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 60
 

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  # Load default data (Needs DB up and running)
  loaddata:
    build: .
    command: bash loaddata.sh
    volumes:
      - .:/app
      - ./filmservice:/fs
    depends_on:
      web:
        condition: service_started
      db:
        condition: service_healthy

  # Service to update films
  filmservice:
    build: FilmService
    command: sh -c "python -u manage.py qcluster & python -u manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./filmservice:/fs
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
