# Generated by Django 4.1.7 on 2023-03-30 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEFlix', '0005_accounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
