# Generated by Django 4.2 on 2023-04-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0006_balance'),
        ('UWEFlix', '0008_remove_club_contacts_club_email_club_phone_number_and_more'),
    ]

    operations = [
    ]
