# Generated by Django 4.2 on 2023-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlix', '0009_merge_20230419_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.AddField(
            model_name='accounting',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
